In [1]:
import os

os.chdir(r"C:\Users\HP USER\OneDrive\Desktop\transfer-learning-kaduna-house-price")

print("Current folder:", os.getcwd())
print("Files in data folder:", os.listdir("data"))

Current folder: C:\Users\HP USER\OneDrive\Desktop\transfer-learning-kaduna-house-price
Files in data folder: ['data_kaggle.csv', 'Strict_Kaduna_South_Dataset.csv']

In [2]:
import pandas as pd
import numpy as np

In [3]:
kaduna_df = pd.read_csv("data/Strict_Kaduna_South_Dataset.csv")

print("Kaduna original shape:", kaduna_df.shape)
print(kaduna_df.columns.tolist())

kaduna_df.head()

Kaduna original shape: (37, 11)
['Property_Type', 'Bedrooms', 'Bathrooms', 'Size_sqm', 'Location', 'LGA', 'Condition', 'Security', 'Flood_Risk', 'Proximity', 'Price']

,Property_Type,Bedrooms,Bathrooms,Size_sqm,Location,LGA,Condition,Security,Flood_Risk,Proximity,Price
0,Bungalow,3,2,140,Barnawa,Kaduna South,New,High,Low,Near,48000000
1,Bungalow,3,2,150,Barnawa,Kaduna South,New,High,Low,Near,52000000
2,Bungalow,3,2,135,Barnawa,Kaduna South,Fair,Medium,Low,Near,43000000
3,Bungalow,3,2,145,Barnawa,Kaduna South,New,High,Low,Near,50000000
4,Flat,2,2,100,Kakuri,Kaduna South,Fair,Medium,Medium,Near,25000000

In [4]:
kaduna_df['Condition'].unique()

<StringArray>
['New', 'Fair', 'Old', 'Good', 'Excellent', 'Poor']
Length: 6, dtype: str

In [5]:
kaduna_df['Property_Type'].unique()

<StringArray>
['Bungalow', 'Flat', 'Duplex', 'Self-contain']
Length: 4, dtype: str

In [6]:
# Load original raw datasets before any preprocessing
malaysia_raw = pd.read_csv("data/data_kaggle.csv")
kaduna_raw   = pd.read_csv("data/Strict_Kaduna_South_Dataset.csv")

print("Datasets loaded successfully.")
print(f"\nMalaysia shape : {malaysia_raw.shape}")
print(f"Kaduna shape   : {kaduna_raw.shape}")

Datasets loaded successfully.

Malaysia shape : (53883, 8)
Kaduna shape   : (37, 11)

In [10]:
malaysia_raw.head()

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
0,"KLCC, Kuala Lumpur","RM 1,250,000",2+1,3.0,2.0,Serviced Residence,"Built-up : 1,335 sq. ft.",Fully Furnished
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,NaN,Bungalow,Land area : 6900 sq. ft.,Partly Furnished
2,"Dutamas, Kuala Lumpur","RM 1,030,000",3,4.0,2.0,Condominium (Corner),"Built-up : 1,875 sq. ft.",Partly Furnished
3,"Cheras, Kuala Lumpur",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Bukit Jalil, Kuala Lumpur","RM 900,000",4+1,3.0,2.0,Condominium (Corner),"Built-up : 1,513 sq. ft.",Partly Furnished

In [11]:
import sklearn
print(sklearn.__version__)

1.8.0